#!/usr/bin/sh

day=$(date --date=+"$1 day" +%m-%d-%Y)
folder="$day"
mkdir -p ./days/$folder
cd ./days/$folder
cat << EOF > planner.adoc
= Planner | $day
:docinfo: shared
:source-highlighter: pygments
:pygments-style: monokai
:icons: font
:stem:
:toc: left
:docinfodir: ../..

[%header, cols="1,1,1"]
|===
| Time | Activity  | Details
|===
EOF
nvim planner.adoc


